### ISSUE TITLE
Not really an issue, rather an remark - broken resolution "fix" between 1.6 and 1.62.

### ISSUE THREAD

**Issue by TzOk83** [th-otto/tos1x#1]
It was possible to make TOS 1.60 (aka 1.06) to boot in medium resolution. If desktop was saved in high resolution (with mono monitor), and color monitor was connected, it was booting in medium resolution. This was quite useful, because utility programs were usually requiring either high or medium resolution.

TOS 1.62 actually broke that useful feature, and there, if desktop is saved in high resolution, and then color monitor is connected, it boots in low resolution.

Same patch was applied on TOS 1.06 by STE_FIX.PRG. Yet that patch was doing one more thing, which is NOT patched in 1.62 - it was synchronizing the system time with IKBD via XBIOS call. This doesn't work either on 1.06, nor in 1.62, but STE_FIX makes the time sync'd during boot even on TOS 1.62, despite the fact it says it is not for this version.

**Comment by th-otto** [comment]
You are right, but the main purpose of this repo is to be able to produce binary identical TOS version from sources. Applying patches for fixes, or generally fixing bugs, is beyond the scope of this project. You are free to do that for your own purpose of course, just make clear that the modified version is not an original, and clearly document what you have changed  if you also make the modified binaries available.

**Comment by TzOk83** [comment]
Yes, I'm aware of the purpose of this repo, that's why I've described this as a remark, not an issue. It was more add-on to the comments you put in the readme file.
